# Generated by Django 6.0.2 on 2026-02-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('kelishilgan', 'Kelishilgan'), ('sotib olingan', 'Sotib olingan'), ('bekor qilingan', 'Bekor qilingan')], default='kutilyapti', max_length=20)),
                ('meeting_location', models.CharField(blank=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
