# Generated by Django 6.0.2 on 2026-02-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('yangi', 'Yangi'), ('ideal', 'Ideal'), ('yaxshi', 'Yaxshi'), ('qoniqarli', 'Qoniqarli')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[("qat'iy", "Qat'iy"), ('kelishiladi', 'Kelishiladi'), ('bepul', 'Bepul'), ('ayirboshlash', 'Ayirboshlash')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('moderatsiyada', 'Moderatsiyada'), ('aktiv', 'Aktiv'), ('rad_etilgan', 'Rad etilgan'), ('sotilgan', 'Sotilgan'), ('arxivlangan', 'Arxivlangan')], default='moderatsiyada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
    ]
